//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute prices.
        /// </summary>
        internal static string AbsolutePrices {
            get {
                return ResourceManager.GetString("AbsolutePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ActiveState {
            get {
                return ResourceManager.GetString("ActiveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This channel is already in queue. It was put into queue by {0}. Current status is {1}..
        /// </summary>
        internal static string ActualizeMessageAlreadyInQueue {
            get {
                return ResourceManager.GetString("ActualizeMessageAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel has been posted into import queue..
        /// </summary>
        internal static string ActualizeMessagePostedIntoQueue {
            get {
                return ResourceManager.GetString("ActualizeMessagePostedIntoQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new category.
        /// </summary>
        internal static string CategoriesEfTitleCreate {
            get {
                return ResourceManager.GetString("CategoriesEfTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category&apos;s properties.
        /// </summary>
        internal static string CategoriesEfTitleEdit {
            get {
                return ResourceManager.GetString("CategoriesEfTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificator.
        /// </summary>
        internal static string CategoryEfInternalId {
            get {
                return ResourceManager.GetString("CategoryEfInternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string CategoryEfName {
            get {
                return ResourceManager.GetString("CategoryEfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ChannelDeleteCommand {
            get {
                return ResourceManager.GetString("ChannelDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ChannelEditCommand {
            get {
                return ResourceManager.GetString("ChannelEditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active?.
        /// </summary>
        internal static string ChannelEfActive {
            get {
                return ResourceManager.GetString("ChannelEfActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales channel properties.
        /// </summary>
        internal static string ChannelEfHeader {
            get {
                return ResourceManager.GetString("ChannelEfHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting to:.
        /// </summary>
        internal static string ChannelEfReportingTo {
            get {
                return ResourceManager.GetString("ChannelEfReportingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new sales channel.
        /// </summary>
        internal static string ChannelEfTitleCreate {
            get {
                return ResourceManager.GetString("ChannelEfTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sales channel properties:.
        /// </summary>
        internal static string ChannelEfTitleEdit {
            get {
                return ResourceManager.GetString("ChannelEfTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string ChannelHistoryCommand {
            get {
                return ResourceManager.GetString("ChannelHistoryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed type.
        /// </summary>
        internal static string ChannelInfoType {
            get {
                return ResourceManager.GetString("ChannelInfoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string ChannelIsActive {
            get {
                return ResourceManager.GetString("ChannelIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ChannelLogState {
            get {
                return ResourceManager.GetString("ChannelLogState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string ChannelMapCommand {
            get {
                return ResourceManager.GetString("ChannelMapCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting To.
        /// </summary>
        internal static string ChannelReportingTo {
            get {
                return ResourceManager.GetString("ChannelReportingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ChannelType {
            get {
                return ResourceManager.GetString("ChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string ChannelUrl {
            get {
                return ResourceManager.GetString("ChannelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price history of {0} ({1}-{2}).
        /// </summary>
        internal static string ChartHeader {
            get {
                return ResourceManager.GetString("ChartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differences Only.
        /// </summary>
        internal static string DefferencesOnly {
            get {
                return ResourceManager.GetString("DefferencesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string DetailsCategory {
            get {
                return ResourceManager.GetString("DetailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string DetailsGeneralTitle {
            get {
                return ResourceManager.GetString("DetailsGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN:.
        /// </summary>
        internal static string DetailsProductEan {
            get {
                return ResourceManager.GetString("DetailsProductEan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name:.
        /// </summary>
        internal static string DetailsProductName {
            get {
                return ResourceManager.GetString("DetailsProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended price:.
        /// </summary>
        internal static string DetailsRecommendedPrice {
            get {
                return ResourceManager.GetString("DetailsRecommendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors:.
        /// </summary>
        internal static string DistributorsLabel {
            get {
                return ResourceManager.GetString("DistributorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditFormCancel {
            get {
                return ResourceManager.GetString("EditFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        internal static string EditFormConfirm {
            get {
                return ResourceManager.GetString("EditFormConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditFormEdit {
            get {
                return ResourceManager.GetString("EditFormEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditFormUpdate {
            get {
                return ResourceManager.GetString("EditFormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon - credentials notification.
        /// </summary>
        internal static string EmailCredentialsSubject {
            get {
                return ResourceManager.GetString("EmailCredentialsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is: {0}. Your password is: {1}..
        /// </summary>
        internal static string EmailCredentialsText {
            get {
                return ResourceManager.GetString("EmailCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon - changing password notification.
        /// </summary>
        internal static string EmailPasswordChangingSubject {
            get {
                return ResourceManager.GetString("EmailPasswordChangingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is: {0}..
        /// </summary>
        internal static string EmailPasswordChangingText {
            get {
                return ResourceManager.GetString("EmailPasswordChangingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon - email reminding notification.
        /// </summary>
        internal static string EmailRemindEmailSubject {
            get {
                return ResourceManager.GetString("EmailRemindEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is: {0}.
        ///If you want to change your password click &lt;a href=&quot;{1}&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string EmailRemindEmailText {
            get {
                return ResourceManager.GetString("EmailRemindEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorType {
            get {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        internal static string ExcludedState {
            get {
                return ResourceManager.GetString("ExcludedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to fill all untranslated resources with default english values?.
        /// </summary>
        internal static string FillUntranslatedResourcesConfirmation {
            get {
                return ResourceManager.GetString("FillUntranslatedResourcesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to channel.
        /// </summary>
        internal static string GoToChannel {
            get {
                return ResourceManager.GetString("GoToChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ImportLogComboDefault {
            get {
                return ResourceManager.GetString("ImportLogComboDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificator.
        /// </summary>
        internal static string InternalId {
            get {
                return ResourceManager.GetString("InternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string LanguageCzech {
            get {
                return ResourceManager.GetString("LanguageCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LogStatus {
            get {
                return ResourceManager.GetString("LogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map and Save.
        /// </summary>
        internal static string MapAndSave {
            get {
                return ResourceManager.GetString("MapAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Mapping.
        /// </summary>
        internal static string MappingActual {
            get {
                return ResourceManager.GetString("MappingActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MappingCustomMapHistory {
            get {
                return ResourceManager.GetString("MappingCustomMapHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mapping.
        /// </summary>
        internal static string MappingCustomMapManual {
            get {
                return ResourceManager.GetString("MappingCustomMapManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string MappingEan {
            get {
                return ResourceManager.GetString("MappingEan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon Product Name.
        /// </summary>
        internal static string MappingName {
            get {
                return ResourceManager.GetString("MappingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Mapping.
        /// </summary>
        internal static string MappingRecommended {
            get {
                return ResourceManager.GetString("MappingRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string MappingState {
            get {
                return ResourceManager.GetString("MappingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Differences Only.
        /// </summary>
        internal static string NegativeDifferencesOnly {
            get {
                return ResourceManager.GetString("NegativeDifferencesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Differences Only.
        /// </summary>
        internal static string PositiveDifferencesOnly {
            get {
                return ResourceManager.GetString("PositiveDifferencesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string PriceDate {
            get {
                return ResourceManager.GetString("PriceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceValue {
            get {
                return ResourceManager.GetString("PriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price inc. VAT.
        /// </summary>
        internal static string PriceVat {
            get {
                return ResourceManager.GetString("PriceVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price with VAT.
        /// </summary>
        internal static string PriceWithVat {
            get {
                return ResourceManager.GetString("PriceWithVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        internal static string ProductCategorie {
            get {
                return ResourceManager.GetString("ProductCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string ProductEan {
            get {
                return ResourceManager.GetString("ProductEan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Price.
        /// </summary>
        internal static string RecommendedPrice {
            get {
                return ResourceManager.GetString("RecommendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative prices.
        /// </summary>
        internal static string RelativePrices {
            get {
                return ResourceManager.GetString("RelativePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        internal static string RelevancePercent {
            get {
                return ResourceManager.GetString("RelevancePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 rows.
        /// </summary>
        internal static string Rows10 {
            get {
                return ResourceManager.GetString("Rows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 rows.
        /// </summary>
        internal static string Rows100 {
            get {
                return ResourceManager.GetString("Rows100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 rows.
        /// </summary>
        internal static string Rows1000 {
            get {
                return ResourceManager.GetString("Rows1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 rows.
        /// </summary>
        internal static string Rows50 {
            get {
                return ResourceManager.GetString("Rows50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 rows.
        /// </summary>
        internal static string Rows500 {
            get {
                return ResourceManager.GetString("Rows500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eShops:.
        /// </summary>
        internal static string ShopsLabel {
            get {
                return ResourceManager.GetString("ShopsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not mapped.
        /// </summary>
        internal static string UnMappedState {
            get {
                return ResourceManager.GetString("UnMappedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        internal static string UsersEfCategories {
            get {
                return ResourceManager.GetString("UsersEfCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string UsersEfCategoriesRights {
            get {
                return ResourceManager.GetString("UsersEfCategoriesRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string UsersEfChannelsRights {
            get {
                return ResourceManager.GetString("UsersEfChannelsRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send daily log.
        /// </summary>
        internal static string UsersEfDailyLog {
            get {
                return ResourceManager.GetString("UsersEfDailyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string UsersEfEmail {
            get {
                return ResourceManager.GetString("UsersEfEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string UsersEfFullName {
            get {
                return ResourceManager.GetString("UsersEfFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General info:.
        /// </summary>
        internal static string UsersEfGeneralInfo {
            get {
                return ResourceManager.GetString("UsersEfGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string UsersEfPassword {
            get {
                return ResourceManager.GetString("UsersEfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string UsersEfProductsRights {
            get {
                return ResourceManager.GetString("UsersEfProductsRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights:.
        /// </summary>
        internal static string UsersEfRights {
            get {
                return ResourceManager.GetString("UsersEfRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Log.
        /// </summary>
        internal static string UsersEfStatusLogRights {
            get {
                return ResourceManager.GetString("UsersEfStatusLogRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        internal static string UsersEfTitleCreate {
            get {
                return ResourceManager.GetString("UsersEfTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user&apos;s properties.
        /// </summary>
        internal static string UsersEfTitleEdit {
            get {
                return ResourceManager.GetString("UsersEfTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UsersEfUsername {
            get {
                return ResourceManager.GetString("UsersEfUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersEfUsersRights {
            get {
                return ResourceManager.GetString("UsersEfUsersRights", resourceCulture);
            }
        }
    }
}
