//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Headers", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring history of {0}.
        /// </summary>
        internal static string ChannelsHistoryPopupForm {
            get {
                return ResourceManager.GetString("ChannelsHistoryPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected products to Excel.
        /// </summary>
        internal static string ExportToExcelHeader {
            get {
                return ResourceManager.GetString("ExportToExcelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login form.
        /// </summary>
        internal static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring details of {0} ({1}).
        /// </summary>
        internal static string MainLogErrorPopupForm {
            get {
                return ResourceManager.GetString("MainLogErrorPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping history of {0}.
        /// </summary>
        internal static string MappingHistoryPopupForm {
            get {
                return ResourceManager.GetString("MappingHistoryPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products import log.
        /// </summary>
        internal static string ProductImportPopupForm {
            get {
                return ResourceManager.GetString("ProductImportPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended price changes history.
        /// </summary>
        internal static string RecommendedHistoryPopupForm {
            get {
                return ResourceManager.GetString("RecommendedHistoryPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind password.
        /// </summary>
        internal static string RemindPassword {
            get {
                return ResourceManager.GetString("RemindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Log.
        /// </summary>
        internal static string StatusLog {
            get {
                return ResourceManager.GetString("StatusLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import products.
        /// </summary>
        internal static string UploadImportPopupForm {
            get {
                return ResourceManager.GetString("UploadImportPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
