//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validators", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number ({0}) can&apos;t be parsed.
        /// </summary>
        internal static string CantParseNumber {
            get {
                return ResourceManager.GetString("CantParseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category code is already exist.
        /// </summary>
        internal static string CategoryCodeAlreadyExist {
            get {
                return ResourceManager.GetString("CategoryCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category identificator must be set.
        /// </summary>
        internal static string CategoryIdMustBeSet {
            get {
                return ResourceManager.GetString("CategoryIdMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is already exist.
        /// </summary>
        internal static string CategoryNameAlreadyExist {
            get {
                return ResourceManager.GetString("CategoryNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name must be set.
        /// </summary>
        internal static string CategoryNameMustBeSet {
            get {
                return ResourceManager.GetString("CategoryNameMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of emails in ReportingTo is not valid email.
        /// </summary>
        internal static string ChannelEmailsAreNotValid {
            get {
                return ResourceManager.GetString("ChannelEmailsAreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info type must be selected.
        /// </summary>
        internal static string ChannelInfoTypeMustBeSet {
            get {
                return ResourceManager.GetString("ChannelInfoTypeMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel name must be defined.
        /// </summary>
        internal static string ChannelNameMustBeSet {
            get {
                return ResourceManager.GetString("ChannelNameMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel type must be selected.
        /// </summary>
        internal static string ChannelTypeMustBeSet {
            get {
                return ResourceManager.GetString("ChannelTypeMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must be defined.
        /// </summary>
        internal static string ChannelUrlMustBeSet {
            get {
                return ResourceManager.GetString("ChannelUrlMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid.
        /// </summary>
        internal static string EmailFormatValidator {
            get {
                return ResourceManager.GetString("EmailFormatValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is a required field.
        /// </summary>
        internal static string EmailRequiredValidator {
            get {
                return ResourceManager.GetString("EmailRequiredValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rows are selected. Please select....
        /// </summary>
        internal static string EmptySelectionError {
            get {
                return ResourceManager.GetString("EmptySelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was imported successfully.
        /// </summary>
        internal static string FileImportedSuccessfully {
            get {
                return ResourceManager.GetString("FileImportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during file import.
        /// </summary>
        internal static string GeneralFileImportError {
            get {
                return ResourceManager.GetString("GeneralFileImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during record import (product {0}).
        /// </summary>
        internal static string GeneralRecordImportError {
            get {
                return ResourceManager.GetString("GeneralRecordImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is too big.
        /// </summary>
        internal static string MaxFileSizeErrorText {
            get {
                return ResourceManager.GetString("MaxFileSizeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no price defined for product {0} ({1}).
        /// </summary>
        internal static string NoPriceForProductError {
            get {
                return ResourceManager.GetString("NoPriceForProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is not allowed for uploading.
        /// </summary>
        internal static string NotAllowedContentTypeError {
            get {
                return ResourceManager.GetString("NotAllowedContentTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is a required field.
        /// </summary>
        internal static string PasswordRequiredValidator {
            get {
                return ResourceManager.GetString("PasswordRequiredValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete category. There are assigned products for category.
        /// </summary>
        internal static string ProductsExistDuringCategoryDelete {
            get {
                return ResourceManager.GetString("ProductsExistDuringCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be in correct format.
        /// </summary>
        internal static string UserEmailMustBeInCorrectFormat {
            get {
                return ResourceManager.GetString("UserEmailMustBeInCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be set.
        /// </summary>
        internal static string UserEmailMustBeSet {
            get {
                return ResourceManager.GetString("UserEmailMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name must be set.
        /// </summary>
        internal static string UserFullNameMustBeSet {
            get {
                return ResourceManager.GetString("UserFullNameMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a user in the DB with the same username or email.
        /// </summary>
        internal static string UserNameAndEmailMustBeUnique {
            get {
                return ResourceManager.GetString("UserNameAndEmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be set.
        /// </summary>
        internal static string UserNameMustBeSet {
            get {
                return ResourceManager.GetString("UserNameMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is a required field.
        /// </summary>
        internal static string UserNameRequiredValidator {
            get {
                return ResourceManager.GetString("UserNameRequiredValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be set.
        /// </summary>
        internal static string UserPasswordMustBeSet {
            get {
                return ResourceManager.GetString("UserPasswordMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml file for channel {0} can&apos;t be downloaded.
        /// </summary>
        internal static string XmlChannelDownloadError {
            get {
                return ResourceManager.GetString("XmlChannelDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml channel is empty (no valid products found).
        /// </summary>
        internal static string XmlChannelEmptyError {
            get {
                return ResourceManager.GetString("XmlChannelEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml file for channel {0} can&apos;t be parsed.
        /// </summary>
        internal static string XmlChannelParseError {
            get {
                return ResourceManager.GetString("XmlChannelParseError", resourceCulture);
            }
        }
    }
}
