//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonWebApp {
    
    
    public partial class Administration {
        
        /// <summary>
        /// AdministrationPageCallbackPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel AdministrationPageCallbackPanel;
        
        /// <summary>
        /// PanelContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxRoundPanel.PanelContent PanelContent1;
        
        /// <summary>
        /// AdministrationPageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxTabControl.ASPxPageControl AdministrationPageControl;
        
        /// <summary>
        /// DistributorsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Code.Controls.CanonPanel DistributorsPanel;
        
        /// <summary>
        /// AdminDistributorsCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Controls.AdminDistributorsImport AdminDistributorsCtrl;
        
        /// <summary>
        /// PricesPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Code.Controls.CanonPanel PricesPanel;
        
        /// <summary>
        /// AdminPricesCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Controls.AdminPricesImport AdminPricesCtrl;
        
        /// <summary>
        /// ProductsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Code.Controls.CanonPanel ProductsPanel;
        
        /// <summary>
        /// AdminResellersCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Controls.AdminResellersImport AdminResellersCtrl;
        
        /// <summary>
        /// DistributorsManagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Code.Controls.CanonPanel DistributorsManagePanel;
        
        /// <summary>
        /// AdminDistributorsManageCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Controls.AdminDistributorsManage AdminDistributorsManageCtrl;
        
        /// <summary>
        /// GroupsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Code.Controls.CanonPanel GroupsPanel;
        
        /// <summary>
        /// AdminGroupsCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Controls.AdminGroups AdminGroupsCtrl;
        
        /// <summary>
        /// AdminUsersPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Code.Controls.CanonPanel AdminUsersPanel;
        
        /// <summary>
        /// AdminUsersCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CanonWebApp.Controls.AdminUsers AdminUsersCtrl;
    }
}
